echo $'---\nlayout: tag_index\ntag: engine \n---' > 'engine.md' &
echo $'---\nlayout: tag_index\ntag: shader \n---' > 'shader.md' &
echo $'---\nlayout: tag_index\ntag: shadows \n---' > 'shadows.md' &
echo $'---\nlayout: tag_index\ntag: threading \n---' > 'threading.md' &
echo $'---\nlayout: tag_index\ntag: ai \n---' > 'ai.md' &
echo $'---\nlayout: tag_index\ntag: navigation \n---' > 'navigation.md' &
echo $'---\nlayout: tag_index\ntag: pathfinding \n---' > 'pathfinding.md' &
echo $'---\nlayout: tag_index\ntag: physx \n---' > 'physx.md' &
echo $'---\nlayout: tag_index\ntag: network \n---' > 'network.md' &
echo $'---\nlayout: tag_index\ntag: cryo \n---' > 'cryo.md' &